name: build

on:
   push:
      paths-ignore:
         - 'doc/**'
         - '*.md'
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3
            with:
               fetch-depth: 0

         -  name: Run tests
            run: ./gradlew check

         -  name: Bundle the build report
            if: failure()
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@master
            with:
               name: error-report
               path: build-reports.zip

   deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3
            with:
               fetch-depth: 0

         -  name: deploy to sonatype snapshots
            run: ./gradlew publish
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
